In [4]:
import pandas as pd
import numpy as np

import os
import glob

In [5]:
# Log file from psychopy.
path_search=os.path.join('..',
                    'data', 
                    'logfiles_task01', 
                    'sub-01_BrainplaybackQuadrants_*_run-1.csv')

log_fn = glob.glob(path_search)[0]

In [6]:
#create a new lists by parsing the string using "," delimiter

head_tail = os.path.split(log_fn)
print(head_tail[1])

sub_id=head_tail[1].split("_")

print("Participant: ",sub_id[0])

run_id=sub_id[-1].split(".")
print("Run id: ",run_id[0])

sub-01_BrainplaybackQuadrants_2022-11-23_15h00.32.477_run-1.csv
Participant:  sub-01
Run id:  run-1

In [7]:
# run data
sub_id=sub_id[0]
run_id=run_id[0]

# default values
sess_id='01'
task_id='01c'

In [8]:
# Create pandas dataframe to read data into data structure.
df_log=pd.read_csv(log_fn)

In [9]:
df_log.columns

Index(['MusicsSelect', 'musics', 'trials.thisRepN', 'trials.thisTrialN',
       'trials.thisN', 'trials.thisIndex', 'blocks.thisRepN',
       'blocks.thisTrialN', 'blocks.thisN', 'blocks.thisIndex',
       'trialsMusics.thisRepN', 'trialsMusics.thisTrialN',
       'trialsMusics.thisN', 'trialsMusics.thisIndex',
       'WelcomeMessage.started', 'WelcomeMessage.stopped', 'Baseline1.started',
       'Noise.started', 'Baseline1.stopped', 'Baseline2.started',
       'MusicExcerpt.started', 'ISI.started', 'MusicExcerpt.stopped',
       'ISI.stopped', 'Noise.stopped', 'Baseline2.stopped',
       'Baseline3.started', 'GoodbyeText.started', 'Baseline3.stopped',
       'GoodbyeText.stopped', 'participant', 'session', 'trigger', 'date',
       'expName', 'psychopyVersion', 'frameRate', 'Unnamed: 37'],
      dtype='object')

In [10]:
# Select subset of columns
df_log_M=df_log.loc[:,["MusicsSelect", "musics","Baseline1.started", "Noise.started","Baseline2.started", "MusicExcerpt.started", "MusicExcerpt.stopped"]]

In [11]:
df_log_M

,MusicsSelect,musics,Baseline1.started,Noise.started,Baseline2.started,MusicExcerpt.started,MusicExcerpt.stopped
0,MusicListQ4.csv,music\Q4\MT0003778826.wav,36.028393,47.976260,59.983276,72.043954,83.544960
1,MusicListQ4.csv,music\Q4\MT0000922312.wav,NaN,NaN,NaN,84.029455,95.535130
2,MusicListQ4.csv,music\Q4\MT0033461826.wav,NaN,NaN,NaN,96.029848,107.534947
3,MusicListQ4.csv,NaN,NaN,NaN,NaN,NaN,NaN
4,MusicListQ1.csv,music\Q1\MT0001680969.wav,107.986501,119.981252,131.985171,144.030033,155.534773
5,MusicListQ1.csv,music\Q1\MT0003669917.wav,NaN,NaN,NaN,156.013833,167.525359
6,MusicListQ1.csv,music\Q1\MT0032405040.wav,NaN,NaN,NaN,168.047581,179.555192
7,MusicListQ1.csv,NaN,NaN,NaN,NaN,NaN,NaN
8,MusicListQ3.csv,music\Q3\MT0003053135.wav,179.994732,191.981860,203.993576,216.065325,227.573774
9,MusicListQ3.csv,music\Q3\MT0001284801.wav,NaN,NaN,NaN,228.032462,239.544062
10,MusicListQ3.csv,music\Q3\MT0031951901.wav,NaN,NaN,NaN,240.049999,251.555337
11,MusicListQ3.csv,NaN,NaN,NaN,NaN,NaN,NaN
12,MusicListQ2.csv,music\Q2\MT0001962373.wav,251.993818,263.984494,275.995376,288.068546,299.575848
13,MusicListQ2.csv,music\Q2\MT0004447086.wav,NaN,NaN,NaN,300.018340,311.525502
14,MusicListQ2.csv,music\Q2\MT0033097471.wav,NaN,NaN,NaN,312.052736,323.554977
15,MusicListQ2.csv,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,MusicListQ4.csv,music\Q4\MT0003454112.wav,324.006033,336.003721,348.006510,360.087821,371.595591
18,MusicListQ4.csv,music\Q4\MT0001394087.wav,NaN,NaN,NaN,372.071569,383.575591
19,MusicListQ4.csv,music\Q4\MT0031886830.wav,NaN,NaN,NaN,384.071969,395.575693
20,MusicListQ4.csv,NaN,NaN,NaN,NaN,NaN,NaN
21,MusicListQ1.csv,music\Q1\MT0003594672.wav,396.042098,408.006177,420.006647,432.040369,443.544546
22,MusicListQ1.csv,music\Q1\MT0031922089.wav,NaN,NaN,NaN,444.057319,455.564745
23,MusicListQ1.csv,music\Q1\MT0002033629.wav,NaN,NaN,NaN,456.024617,467.532098
24,MusicListQ1.csv,NaN,NaN,NaN,NaN,NaN,NaN
25,MusicListQ3.csv,music\Q3\MT0001533920.wav,468.029230,479.992146,491.995427,504.076157,515.585490
26,MusicListQ3.csv,music\Q3\MT0003037596.wav,NaN,NaN,NaN,516.060007,527.565268
27,MusicListQ3.csv,music\Q3\MT0030252676.wav,NaN,NaN,NaN,528.060249,539.565144
28,MusicListQ3.csv,NaN,NaN,NaN,NaN,NaN,NaN
29,MusicListQ2.csv,music\Q2\MT0004293364.wav,540.035345,551.994117,564.011968,576.078872,587.584177
30,MusicListQ2.csv,music\Q2\MT0030214520.wav,NaN,NaN,NaN,588.062613,599.564974
31,MusicListQ2.csv,music\Q2\MT0002385077.wav,NaN,NaN,NaN,600.063060,611.564214
32,MusicListQ2.csv,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Select subset of columns
df_last_bl=df_log.loc[:,["Baseline3.started", "Baseline3.stopped"]]

# Remove rows with NaN - nor necessary for this event files.
df_last_bl=df_last_bl.dropna(how="any")

## Get Quadrants selected by participant

In [ ]:
def getQ(row):  
    t = row['music.id'].split('/')
    return (f'{t[3]}')

def categorise(row):  
    if row['mouse.x'] > 0 and row['mouse.y'] > 0:
        return 'Q1'
    elif row['mouse.x'] < 0 and row['mouse.y'] > 0:
        return 'Q2'
    elif row['mouse.x'] < 0  and row['mouse.y'] < 0:
        return 'Q3'
    return 'Q4'

In [ ]:
full_list = os.listdir(os.path.join('..',
                    'music_characterization_stim', 
                    'data'))


# list to store files
csv_file = []

# participant idx
p = sub_id.split('-')[1]

# run idx
r = run_id.split('-')[1]
r = str(r).zfill(2)

print("Participant (idx), run (idx): ",p, r)



# identify csv file for each run
tok_filename = f'{p}_{r}'

# Iterate directory
for file in full_list:
    # check only text files
    if file.startswith(tok_filename) and file.endswith('.csv'):
        csv_file.append(file)
        
df_Q = pd.read_csv(os.path.join('..',
                    'music_characterization_stim', 
                    'data', 
                    csv_file[0]))

# Last row NaN.
df_Q = df_Q[:24]
    
# Select rows of interest.
df_Q=df_Q[['music.id','mouse.x','mouse.y']]

# Extract position from mouse columns.
df_Q['mouse.x'] = df_Q['mouse.x'].str[1:-1].astype(float)
df_Q['mouse.y'] = df_Q['mouse.y'].str[1:-1].astype(float)

# extract Q from music filename.
df_Q['music.id_project'] = df_Q.apply(lambda row: getQ(row), axis=1)

# Get Q from mouse click position.
df_Q['Quadrants.participant'] = df_Q.apply(lambda row: categorise(row), axis=1)

# select each music and look for new id
df_log_M['musics']

QperPart=[]

for index, row in df_log_M.iterrows():
    #print(index, row['musics'])
    if row['musics'] == row['musics']:
        toks=row['musics'].split("\\")
        musictok=toks[2]
        # print(musictok, toks[1], index)
        
        #find music in classification dataframe
        musics_dfQ = df_Q.loc[df_Q['music.id'].str.contains(musictok, case=False)]
        
        (musics_dfQ['Quadrants.participant'].values[0])
        QperPart.append(musics_dfQ['Quadrants.participant'].values[0])
    else:
        QperPart.append(np.NaN)
        

# print(QperPart)
df_log_M['musicsQperPart'] = QperPart

df_log_M.head(10)

## Create BIDS

In [ ]:
# Create pandas dataframe with columns required by the BIDS standard.
bids={'onset':[],'duration':[],'trial_type':[]}
df_bids=pd.DataFrame(bids)

In [ ]:
#number of decimals when rounding numbers
decimals=2

# offset of the experiment in seconds (seconds until first baseline.)
exp_offset=df_log_M.iloc[0]["Baseline1.started"]

# considering the log file, add rows for each event.

# For each row:
for i in range(len(df_log_M)-1):
    if not np.isnan(df_log_M.iloc[i]["Baseline1.started"]):
        # Add Baseline trial.
        df_bids.loc[len(df_bids.index)] = [np.round(df_log_M.iloc[i]["Baseline1.started"]-exp_offset, decimals),
                                           np.round(df_log_M.iloc[i]["Noise.started"]-df_log_M.iloc[i]["Baseline1.started"],
                                                    decimals),
                                          'Baseline'] 
        # Add Noise trial.
        df_bids.loc[len(df_bids.index)] = [np.round(df_log_M.iloc[i]["Noise.started"]-exp_offset, decimals),
                                           np.round(df_log_M.iloc[i]["Baseline2.started"]-df_log_M.iloc[i]["Noise.started"],
                                                    decimals),
                                          'Noise'] 
        # Add Baseline2 trial.
        df_bids.loc[len(df_bids.index)] = [np.round(df_log_M.iloc[i]["Baseline2.started"]-exp_offset, decimals),
                                           np.round(df_log_M.iloc[i]["MusicExcerpt.started"]-df_log_M.iloc[i]["Baseline2.started"],
                                                    decimals),
                                          'Baseline'] 

        # Add Music trial.
        df_bids.loc[len(df_bids.index)] = [np.round(df_log_M.iloc[i]["MusicExcerpt.started"]-exp_offset, decimals),
                                           np.round(df_log_M.iloc[i]["MusicExcerpt.stopped"]-df_log_M.iloc[i]["MusicExcerpt.started"], decimals),
                                           df_log_M.iloc[i]["musicsQperPart"]+ '_p'] 
        
        # Add Music trial.
        df_bids.loc[len(df_bids.index)] = [np.round(df_log_M.iloc[i]["MusicExcerpt.started"]-exp_offset, decimals),
                                           np.round(df_log_M.iloc[i]["MusicExcerpt.stopped"]-df_log_M.iloc[i]["MusicExcerpt.started"], decimals),
                                           df_log_M.iloc[i]["MusicsSelect"][-6:-4] + '_db'] 
        
    
    elif not np.isnan(df_log_M.iloc[i]["MusicExcerpt.started"]):
    
        # Add Music trial.
        df_bids.loc[len(df_bids.index)] = [np.round(df_log_M.iloc[i]["MusicExcerpt.started"]-exp_offset, decimals),
                                           np.round(df_log_M.iloc[i]["MusicExcerpt.stopped"]-df_log_M.iloc[i]["MusicExcerpt.started"], decimals),
                                           df_log_M.iloc[i]["musicsQperPart"]+ '_p'] 
        
        # Add Music trial.
        df_bids.loc[len(df_bids.index)] = [np.round(df_log_M.iloc[i]["MusicExcerpt.started"]-exp_offset, decimals),
                                           np.round(df_log_M.iloc[i]["MusicExcerpt.stopped"]-df_log_M.iloc[i]["MusicExcerpt.started"], decimals),
                                           df_log_M.iloc[i]["MusicsSelect"][-6:-4] + '_db']

In [ ]:
df_bids.head(20)

In [ ]:
# Create tsv file.
fn=f"{sub_id}_ses-{sess_id}_task-{task_id}_{run_id}_events.tsv"

print(fn)
df_bids.to_csv(os.path.join('bids-events-files',fn), sep="\t", index=False)

In [ ]:
del df_bids